spring:
  application:
    name: ai-builder-backend
  profiles:
    active: local
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_builder
    username: root
    password: 1234
  # 邮件配置
  mail:
    username: your email
    password: your password
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    valid: 5
    title: "AI Builder - 用户认证"
    template: "您的动态验证码为：<strong style='color: red'>%s</strong>，%d分钟内有效，若非本人操作，请勿泄露。"
  server:
    port: 8123
    servlet:
      context-path: /api
      # cookie 30 天过期
      session:
        cookie:
          max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.miri.aibuilder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-v4-flash
      max-tokens: 8192
      log-requests: true
      log-responses: true
    reasoning-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-guangzhou
    bucket: your-bucket-name
